# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3dc80d338d881fba6f4f9771eec68d011d919e5dcc2c1383a9b79d3162492ecd96ee770c79cedde7374e73ab8ed0b0b6743358e0b00ed28b658b7f007e82a23

test:
  secret_key_base: 8cbac029122dfc03cbefe5ad9e80ecc7d95e1d0522a5f158a83ffbced26b6cefa5fef17e1d6c955844e4329fd8d06a153726854aba248106661ffdd98e16db6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
